//! Budgets are enforced with a cheap runtime estimate; this checks the estimate
//! against a real tokenizer (o200k) so the budgets hold in actual tokens.

use remember_core::model::estimate_tokens;
use remember_core::{Category, Hub, Limits, NewMemory, RecallQuery, Scope};

fn real_tokens(text: &str) -> usize {
    tiktoken_rs::o200k_base_singleton()
        .encode_with_special_tokens(text)
        .len()
}

fn seeded_hub() -> (Hub, String) {
    let mut hub = Hub::open_in_memory(Limits::default()).unwrap();
    let agent = hub
        .register("claude-code", "github.com/avidianity/remember")
        .unwrap();
    let samples = [
        "Use pnpm, never npm, in every JavaScript project.",
        "Auth tokens live in an httpOnly, SameSite=Lax cookie; refresh happens in middleware/auth.rs.",
        "DB migrations are forward-only and run inside an exclusive transaction at startup.",
        "Prefer rusqlite prepare_cached for hot queries; p99 must stay under 10ms at 50k memories.",
        "Tests: `cargo test --workspace`, snapshots via insta, e2e spawns the real binary over stdio.",
        "Kubernetes manifests are generated by `make k8s`, never edited by hand (see deploy/README).",
    ];
    hub.remember(
        &agent,
        NewMemory {
            text: "Reply tersely; JSON output must be TOON.",
            scope: Scope::User,
            category: Category::Fact,
            key: Some("style"),
        },
    )
    .unwrap();
    for n in 0..200 {
        let text = format!("{} (variant {n})", samples[n % samples.len()]);
        let key = format!("topic.{n}");
        hub.remember(
            &agent,
            NewMemory {
                text: &text,
                scope: Scope::Project,
                category: Category::Decision,
                key: Some(&key),
            },
        )
        .unwrap();
    }
    for n in 0..30 {
        hub.start_task(
            &agent,
            &format!(
                "Task number {n}: refactor the {} module",
                samples[n % 6].split(' ').nth(1).unwrap()
            ),
            None,
        )
        .unwrap();
    }
    (hub, agent)
}

#[test]
fn context_payload_fits_budget_in_real_tokens() {
    let (hub, agent) = seeded_hub();
    let context = hub.context(&agent, None).unwrap();
    assert!(context.truncated.is_some(), "seed must overflow the budget");
    let encoded = remember_core::toon::encode(&context).unwrap();
    let real = real_tokens(&encoded);
    assert!(
        real <= hub.limits().context_tokens,
        "context is {real} tokens"
    );
    assert!(
        real >= hub.limits().context_tokens / 2,
        "budget badly underused: {real} tokens"
    );
}

#[test]
fn recall_payload_fits_budget_in_real_tokens() {
    let (hub, agent) = seeded_hub();
    let recall = hub
        .recall(
            &agent,
            &RecallQuery {
                text: Some("auth cookie middleware"),
                limit: Some(50),
                ..Default::default()
            },
        )
        .unwrap();
    let encoded = remember_core::toon::encode(&recall).unwrap();
    let real = real_tokens(&encoded);
    assert!(
        real <= hub.limits().recall_tokens,
        "recall is {real} tokens"
    );
}

#[test]
fn estimate_never_undercounts_typical_text() {
    let (hub, _) = seeded_hub();
    let export = remember_core::toon::encode(&hub.export().unwrap()).unwrap();
    for chunk in export.lines() {
        assert!(
            estimate_tokens(chunk) >= real_tokens(chunk),
            "undercounted: {chunk}"
        );
    }
}
